name: aqueduct_forum_frontend
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  reflectable: any
dev_dependencies:
  browser: ^0.10.0
  http: ^0.11.0
  dart_to_js_script_rewriter: ^1.0.1
  ng_bootstrap: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
- reflectable:
    entry_points:
    - web/main.dart # The path to your main file
